ProductController - wstpna implementacja endpointów
piotr-grosicki/project-jdp-2205-02 pull request #3
Opened 2022-05-04 17:30 UTC by damian8100

2022-05-06 13:01 UTC, piotr-grosicki requested changes
projekt sie nie kompiluje

2022-05-06 16:34 UTC, piotr-grosicki requested changes

2022-05-06 16:34 UTC, piotr-grosicki commented on build.gradle
> +    runtimeOnly 'org.postgresql:postgresql:42.3.3'
nie korzystamy z postgresa

2022-05-06 16:34 UTC, piotr-grosicki commented on build.gradle
>  dependencies {
zmiany w tym pliku powoduja konflikty wzgledem main, nie da sie zmergowac

2022-05-06 16:34 UTC, piotr-grosicki commented on build.gradle
> +    implementation 'org.projectlombok:lombok:1.18.20'
lombok jest dodany dwa razy

2022-05-06 16:34 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/Product.java
> +    public class Product {
w tym zadaniu nie powinna powstac encja

2022-05-06 16:34 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/ProductController.java
> +    public void deleteProduct(Long productId) {
brakuje adnotacji i path variable w sciezce

2022-05-06 16:34 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/ProductController.java
> +    public ProductDto updateProduct(ProductDto productDto){
brakuje adnotacji

2022-05-06 16:34 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/ProductController.java
> +    public void createProduct(ProductDto productDto){
brakuje adnotacji

2022-05-07 10:25 UTC, GregRak commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +@RequestMapping("/v1/product")
trzymaliśmy się tego co było w modułach, więc zmieniłbym na liczbę mnogą - products

2022-05-07 10:33 UTC, GregRak commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    }
Wydaje mi się, że cudzysłów jest w złym miejscu, zmieniłbym na "{productId}"
Long z dużej litery :)

2022-05-07 10:34 UTC, GregRak commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +
cudzysłów j.w.

2022-05-07 10:53 UTC, GregRak commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +
Sugeruję trzymanie się jednej konwencji, wstawialiśmy adnotację @RequestBody i może tak zostawmy

2022-05-07 11:09 UTC, GregRak commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +
Moim zdaniem lepszym pomysłem do typowania cen jest BigDecimal

2022-05-07 11:10 UTC, GregRak commented on src/main/java/com/kodilla/ecommercee/domain/ProductDto.java
> +    private double price;
j.w.

2022-05-09 14:40 UTC, GregRak commented on build.gradle
>      annotationProcessor 'org.projectlombok:lombok:1.18.22'
Mamy już lomboka i mysql-connector w projekcie. Myślę, że możesz dodać swaggera, bo może się przydać, ale w osobnym tasku z Jira.

2022-05-11 12:21 UTC, K-Kasjan reviewed
Dlaczego w tej branchy jest klasa Product która nawet nie jest oznaczona jako Entity? Czy ja źle to rozumiem, czy klasy Product.java oraz ProductDto.java są zduplikowane w pakiecie głównym i domain?

2022-05-11 19:13 UTC, closed without merging