JDP220502 25: UserController - rzeczywista implementacja metod
piotr-grosicki/project-jdp-2205-02 pull request #34
Opened 2022-05-21 18:48 UTC by GregRak

2022-05-22 16:41 UTC, K-Kasjan requested changes
Wydaje mi się, że w ścieżkach dostępu dobrym zwyczajem jest najpierw nazwa zasobu a potem zmienne. Np zamiast "{userId}/{userEmail}/generateToken" - "generateToken/{userId}/{userEmail}" ale nie znalazłem nigdzie potwierdzenia mojej teorii

2022-05-22 16:41 UTC, K-Kasjan commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +    public List<UserDto> getUsers() {
typem zwracanym powinno być ResponseEntity<List<UserDto>>

2022-05-22 21:09 UTC, AdrianGithubpros approved these changes

2022-05-23 19:55 UTC, damian8100 approved these changes

2022-05-23 20:43 UTC, merged